### ISSUE TITLE
Can't find tesserocr of python3.7

### ISSUE THREAD

**Issue by bobli1128** [simonflueckiger/tesserocr-windows_build#1]
Rently Python3.7 has released, so I installed that. But can't find the tesserocr suiting it.
When can we get tesserocer3.7?

**Comment by yy1987316** [comment]
same problem
if wanna use tesser, must I lower python version to 3.6?

**Comment by lxb0852** [comment]
**I am using python3.6** (ಥ_ಥ)

**Comment by wangjinliang1991** [comment]
u can use the tensorflow to handle the image verification code problems, or also use the baiduocr api to do if u can't wait the latest version@yy1987316

**Comment by wangjinliang1991** [comment]
u can use the tensorflow to handle the image verification code problems, or also use the baiduocr api to do if u can't wait the latest version @yy1987316

**Comment by simonflueckiger** [comment]
I'm looking into this. [https://github.com/simonflueckiger/tesserocr-windows_build/issues/2#issuecomment-430663846](https://github.com/simonflueckiger/tesserocr-windows_build/issues/2#issuecomment-430663846)

**Comment by simonflueckiger** [comment]
Can you check if my most recent release [tesserocr-v2.3.1-tesseract-4.0.0-rc3](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.3.1-tesseract-4.0.0-rc3) works for you?
