### ISSUE TITLE
Build for tesseract 5.0.0

### ISSUE THREAD

**Issue by NeutronBlast** [simonflueckiger/tesserocr-windows_build#14]
I'm using Tesseract v5.0.0, Python 3.9.2 and pip v22.0.4 with 64 bits Windows 10 machine and I'm unable to use this package, support for this would be appreciated.

**Comment by simonflueckiger** [comment]
tesserocr 2.5.2 with Tesseract 5.3.0 is now [released](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.5.2-tesseract-5.3.0).
