### ISSUE TITLE
2.6.0 release

### ISSUE THREAD

**Issue by zdenop** [simonflueckiger/tesserocr-windows_build#15]
Can you please release wheel for https://github.com/sirfz/tesserocr/releases/tag/v2.6.0 version?

**Comment by simonflueckiger** [comment]
Of course, here you go: [wheels](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.6.0-tesseract-5.3.1) | [Anaconda](https://anaconda.org/simonflueckiger/tesserocr).
