### ISSUE TITLE
Python 3.12 and version 2.6.2

### ISSUE THREAD

**Issue by toebsen** [simonflueckiger/tesserocr-windows_build#17]
Hi,
thanks for you effort. Is it possible to also build and release tesserocr for 2.62 with python 3.12?

**Comment by iDkGK** [comment]
Looking forward to this, too!

**Comment by rudolphos** [comment]
Same request as well

**Comment by simonflueckiger** [comment]
tesserocr 2.6.2 (including Python 3.12 support) is finally here, sorry for the long wait. You can find it in the [Releases](https://github.com/simonflueckiger/tesserocr-windows_build/releases) section or on [Anaconda](https://anaconda.org/simonflueckiger/tesserocr).
