### ISSUE TITLE
No intellisense with VS-Code

### ISSUE THREAD

**Issue by Alexandros444** [simonflueckiger/tesserocr-windows_build#19]
Hallo, I seem to have no intellisense with vs-code when I install the package via whl.
I have Python3.10, the only content of the __init__.py is `from ._tesserocr import *`, so i don't really know to use the module. :(

Kind Regards Alex

**Comment by simonflueckiger** [comment]
I was able to reproduce this with VSC on my system. Thanks to this [stackoverflow post](https://stackoverflow.com/a/66361707) I found out that the plugin [Pylace](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance&ssr=false#review-details) is most likely the culprit if auto-completion/smart-navigation stops working for Python. [Their Repo](https://github.com/microsoft/pylance-release/issues) is riddled with issues concerning this [[1](https://github.com/microsoft/pylance-release/issues/5284), [2](https://github.com/microsoft/pylance-release/issues/5377), [3](https://github.com/microsoft/pylance-release/issues/5021)]. Disabling the Plugin in VSC made everything work as expected again

![image](https://github.com/simonflueckiger/tesserocr-windows_build/assets/2737827/1aeee5f8-0a9d-499e-b541-bfdeb2f38c5a)
