### ISSUE TITLE
When can you share the windows package？

### ISSUE THREAD

**Issue by zhangluustb** [simonflueckiger/tesserocr-windows_build#2]
When can you share the windows package？

**Comment by simonflueckiger** [comment]
Sorry, it's been a while since this issue was opened, my job hasn't really allowed me to spend any time on this lately. However, I might have a bit more time to spare in the upcoming weeks, so fingers crossed.

**Comment by simonflueckiger** [comment]
Can you check if my most recent release [tesserocr-v2.3.1-tesseract-4.0.0-rc3](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.3.1-tesseract-4.0.0-rc3) works for you?
