### ISSUE TITLE
Release 2.70

### ISSUE THREAD

**Issue by zdenop** [simonflueckiger/tesserocr-windows_build#21]
Can you please release 2.7.0 version?

https://github.com/sirfz/tesserocr/releases/tag/v2.7.0

**Comment by simonflueckiger** [comment]
Version 2.7.0 is now released to [GitHub Releases](https://github.com/simonflueckiger/tesserocr-windows_build/releases) and [Anaconda](https://anaconda.org/simonflueckiger/tesserocr).
