### ISSUE TITLE
'utf-8' codec can't decode byte 0xca in position 3: invalid continuation byte

### ISSUE THREAD

**Issue by zhuazhizhuda** [simonflueckiger/tesserocr-windows_build#25]
import tesserocr

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[10], line 1
----> 1 import tesserocr

File E:\anaconda\Lib\site-packages\tesserocr\__init__.py:1
----> 1 from .tesserocr import __version__
      2 from .tesserocr import *

File tesserocr\\tesserocr.pyx:58, in init tesserocr.tesserocr()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 3: invalid continuation byte

tesserocr version is 2.7.1
tesseract version is 5.4.0

**Comment by simonflueckiger** [comment]
I wasn't able to reproduce the error on my end. Could you please provide more details?
- Steps to reproduce the issue (minimal working example with input data)
- Your operating system and Python version
- How you installed tesserocr and Tesseract (pip or conda)
- Any other standalone Tesseract version installed on your system

**Comment by zhuazhizhuda** [comment]
Thank you for your response. In fact, I have already resolved the issue, but I forgot to close the issue. My Python version is 3.11, and when I downgraded tesserocr to version 2.7.0 and restarted my computer, the import worked normally.
