### ISSUE TITLE
Python 3.13

### ISSUE THREAD

**Issue by chrisoro** [simonflueckiger/tesserocr-windows_build#26]
Could you please add Python 3.13 to the list of interpreters that you build for? Thank you!

**Comment by simonflueckiger** [comment]
Thanks for bringing this to my attention @chrisoro 👍 Python 3.13 builds are now added to the latest builds in [Releases](https://github.com/simonflueckiger/tesserocr-windows_build/releases) and [Anaconda](https://anaconda.org/simonflueckiger/tesserocr).
