### ISSUE TITLE
It's urgent, Can u share the windows package  

### ISSUE THREAD

**Issue by SANDAFERNANDO** [simonflueckiger/tesserocr-windows_build#3]

**Comment by simonflueckiger** [comment]
Yes, I'm looking into this. [https://github.com/simonflueckiger/tesserocr-windows_build/issues/2#issuecomment-430663846](https://github.com/simonflueckiger/tesserocr-windows_build/issues/2#issuecomment-430663846)

**Comment by simonflueckiger** [comment]
Can you check if my most recent release [tesserocr-v2.3.1-tesseract-4.0.0-rc3](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.3.1-tesseract-4.0.0-rc3) works for you?
