### ISSUE TITLE
any plan on packaging the latest release ?

### ISSUE THREAD

**Issue by redstoneleo** [simonflueckiger/tesserocr-windows_build#5]
https://github.com/sirfz/tesserocr/releases

**Comment by EhsanKia** [comment]
Would also like to a see a newer 2.7 release.

**Comment by simonflueckiger** [comment]
@redstoneleo tesserocr 2.4.0 (packaging tesseract 4.0.0 Release) can now be downloaded from the [releases](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.4.0-tesseract-4.0.0) section or via `conda install -c simonflueckiger/label/tesseract-4.0.0-master tesserocr`

**Comment by simonflueckiger** [comment]
@EhsanKia I opened a separate issue https://github.com/simonflueckiger/tesserocr-windows_build/issues/6 regarding your question
