### ISSUE TITLE
More recent Tesseract build

### ISSUE THREAD

**Issue by StephenRUK** [simonflueckiger/tesserocr-windows_build#7]
Hi! The version of Tesseract in this package has a bug which affects our software. I tried to use ccpan to compile the most recent Tesseract 4 DLL and replace it in this package, without success.

It would be great to have a new build with the latest Tesseract release. Or possibly instructions on how to build your conda package with a newer release by ourselves.

Danke!

**Comment by simonflueckiger** [comment]
Hi @StephenRUK! I will look into it today or tomorrow if I find some time. Could you let me know which version I should build for you to test? Python 3.7 64bit? And is there already an existing issue regarding this bug on https://github.com/tesseract-ocr/tesseract where I could find out more, just out of curiosity :)

**Comment by StephenRUK** [comment]
We are working with symbol-level bounding boxes (to do something like [this](https://medium.com/sap-machine-learning-research/chargrid-77aa75e6d605)), and they are sometimes inaccurate when using the new Tesseract 4 engine. I found a few issues on it - e.g. here the bounding boxes work in RC 4,1 https://github.com/tesseract-ocr/tesseract/issues/2240 - on the other hand, this issue is still open for the same problem https://github.com/tesseract-ocr/tesseract/issues/2024

So I am putting my hope in 4.1.0-rc1, which is tagged here: https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.0-rc1 - Python 3.7, 64 Bit, Windows

**Comment by simonflueckiger** [comment]
Alright, here is a wheel bundled with tesseract 4.1.0-rc1. Would you mind giving this a try and report back if it works as intended?
[tesserocr-2.4.0-cp37-cp37m-win_amd64.zip](https://github.com/simonflueckiger/tesserocr-windows_build/files/3089099/tesserocr-2.4.0-cp37-cp37m-win_amd64.zip)

**Comment by StephenRUK** [comment]
Thanks for the new build, Simon. Installation of the whl works fine.

As for the Tesseract issue, it looks like the symbol bounding boxes have changed (I got some improvements) but are not yet fixed. If you're interested, see my example below:

Input:
![somecharacters](https://user-images.githubusercontent.com/9080475/56350511-38c1ef80-61cb-11e9-9e6b-5518c34f8d57.png)

Output symbol bounding box image:

![image](https://user-images.githubusercontent.com/9080475/56350348-e1238400-61ca-11e9-8937-11dbadd8671c.png)

**Comment by simonflueckiger** [comment]
I'm glad to hear that the new build made things a bit better. Really unfortunate that the issue is still around however. Is there anything I can do to help at this point?

**Comment by StephenRUK** [comment]
If it's simple enough, could you explain how to create a new build .whl, or how to replace the Tesseract DLL with an updated one after installation? I noticed your Tesseract DLL has a different name than the original. Otherwise, I'll look back here when there's a new release 😄

**Comment by simonflueckiger** [comment]
Here is the most recent build of the windows tesserocr wheel on my appveyor: https://ci.appveyor.com/project/simonflueckiger/tesserocr-windows-build-8c9xt/builds/23914383. If all the dependencies are met on your system, it's as simple as calling `python setup.py bdist_wheel`. Unfortunately, tesserocr.pyd (after being compiled from tesserocr.pyx) can generally not interface with another tesseract dll [[1]](https://en.wikipedia.org/wiki/DLL_Hell), so it's not as simple as replacing the dll file in the `site-packages/tesserocr` folder.

I'm sorry for not giving you a more satisfactory answer, but feel free to reopen this issue if you want me to build with another tesseract commit that fixes this issue.

**Comment by StephenRUK** [comment]
Perfect, I'll give the build a try when it's time. Thanks again!

**Comment by StephenRUK** [comment]
Hi @simonflueckiger, in the meantime, a fix for the character bounding boxes has been issued. It didn't make release 4.1 but was merged in 2 days ago: https://github.com/tesseract-ocr/tesseract/pull/2576 - a new build would be great whenever you get around to it 👍 (still x64, python 3.7)

**Comment by simonflueckiger** [comment]
Hi @StephenRUK, just letting you know that I'm currently looking into this. I'm running into some building issues, however. Stay tuned.
