### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by XinhhD** [simonflueckiger/tesserocr-windows_build#8]
Running the latest 64-bit tesserocr in Windows10 with python 3.7;
while it shows:
```
 File "tesserocr.pyx", line 54, in init tesserocr._tesserocr
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 7: invalid start byte
```

**Comment by simonflueckiger** [comment]
Hi @XinhhD, I need a bit more to have a chance of reproducing that error on my end. What code were you running with what kind of input?

**Comment by XinhhD** [comment]
> 
> 
> Hi @XinhhD, I need a bit more to have a chance of reproducing that error on my end. What code were you running with what kind of input?

Here is the whole code I were running on my PC
```
import tesserocr
from PIL import Image
import sys

print(sys.getdefaultencoding())
image=Image.open('out.png')
print(tesserocr.image_to_text(image))
```
And the TraceBack shows:
```
Traceback (most recent call last):
  File "C:/Users/xinhhd/PycharmProjects/captcha/demo.py", line 4, in <module>
    import tesserocr
  File "C:\Users\xinhhd\AppData\Local\Programs\Python\Python37\lib\site-packages\tesserocr\__init__.py", line 2, in <module>
    from ._tesserocr import *
  File "tesserocr.pyx", line 54, in init tesserocr._tesserocr
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 7: invalid start byte
```
The error occurs in  **import**

**Comment by simonflueckiger** [comment]
I need your input image `out.png` for a proper test. It works well for the tesseract [eurotext.tif](https://github.com/tesseract-ocr/test/blob/master/testing/eurotext.tif).

**Comment by XinhhD** [comment]
![out](https://user-images.githubusercontent.com/33118163/56354074-79d6f580-6205-11e9-8d14-6bdf79d94605.png)
here is the image.
However, I see the error happens when "**import tesserocr**", which means the line `image=Image.open('out.png')` has not been executed.

**Comment by XinhhD** [comment]
I think this error may be caused by the charset of `tesserocr.pyx`, python using UTF-8 and when it decode the file `tesserocr.pyx` in line 54, here are some non-utf-8 bytes.
I searched in StackOverflow and found that most of the UnicodeDecodeError can be solved by change a decode charset (like using gb2312 or something else instead of utf-8).

**Comment by simonflueckiger** [comment]
Sorry, didn't notice before that the issue is in `tesserocr.pyx`. Not entirely sure how you ended up with the .pyx file, how exactly did you install tesserocr? Did you install from `.whl` or anaconda, or did you build from source?

**Comment by XinhhD** [comment]
> 
> 
> Sorry, didn't notice before that the issue is in `tesserocr.pyx`. Not entirely sure how you ended up with the .pyx file, how exactly did you install tesserocr? Did you install from `.whl` or anaconda, or did you build from source?

I installed the latest release .whl by pip

**Comment by simonflueckiger** [comment]
So in a clean python environment (without any other tesserocr remnants around) you used `pip install tesserocr-2.4.0-cp37-cp37m-win_amd64.whl`?

**Comment by XinhhD** [comment]
python 3.7
pip install tesserocr-2.4.0-cp37-cp37m-win_amd64.whl
windows 10

**Comment by simonflueckiger** [comment]
Alright, could you please post the output of `pip list` and `dir C:\Users\xinhhd\AppData\Local\Programs\Python\Python37\lib\site-packages\tesserocr\`

**Comment by XinhhD** [comment]
dir ouput
```
2019/04/18  21:13    <DIR>          .
2019/04/18  21:13    <DIR>          ..
2019/04/18  21:13         2,571,264 pvt.cppan.demo.danbloomberg.leptonica-1.76.0.dll
2019/04/18  21:13           244,224 pvt.cppan.demo.jpeg-9.2.0.dll
2019/04/18  21:13            86,528 pvt.cppan.demo.madler.zlib-1.2.11.dll
2019/04/18  21:13           284,160 pvt.cppan.demo.openjpeg.openjp2-2.3.0.dll
2019/04/18  21:13           194,560 pvt.cppan.demo.png-1.6.35.dll
2019/04/18  21:13           441,344 pvt.cppan.demo.tiff-4.0.9.dll
2019/04/18  21:13           519,168 pvt.cppan.demo.webp-0.6.1.dll
2019/04/18  21:13           151,552 pvt.cppan.demo.xz_utils.lzma-5.2.4.dll
2019/04/18  21:13         3,222,016 pvt.simonflueckiger.tesseract.libtesseract-4.0.0.dll
2019/04/18  21:13           369,152 _tesserocr.cp37-win_amd64.pyd
2019/04/18  21:13                26 __init__.py
2019/04/18  21:13    <DIR>          __pycache__
```
pip list output
```
Package              Version
-------------------- --------
absl-py              0.7.1
astor                0.7.1
basemap              1.2.0
beautifulsoup4       4.7.1
bs4                  0.0.1
captcha              0.2.2
certifi              2019.3.9
chardet              3.0.4
Click                7.0
cycler               0.10.0
Flask                1.0.2
future               0.17.1
gast                 0.2.2
geos                 0.2.1
grpcio               1.19.0
h5py                 2.9.0
idna                 2.8
itsdangerous         1.1.0
Jinja2               2.10
Keras-Applications   1.0.7
Keras-Preprocessing  1.0.9
kiwisolver           1.0.1
lxml                 4.3.0
Markdown             3.1
MarkupSafe           1.1.0
matplotlib           3.0.2
mock                 2.0.0
numpy                1.16.2
opencv-python        4.1.0.25
pandas               0.24.1
pbr                  5.1.3
Pillow               6.0.0
pip                  19.0.3
protobuf             3.7.1
pyparsing            2.3.0
pyproj               1.9.6
pyshp                2.0.1
python-dateutil      2.7.5
pytz                 2018.9
requests             2.21.0
scikit-learn         0.20.2
scipy                1.2.0
setuptools           39.0.1
six                  1.12.0
soupsieve            1.9.1
tensorboard          1.13.1
tensorflow           1.13.1
tensorflow-estimator 1.13.0
tesserocr            2.4.0
urllib3              1.24.2
wechatsogou          4.5.4
Werkzeug             0.14.1
wheel                0.33.1
xlrd                 1.2.0
```

**Comment by simonflueckiger** [comment]
let's chat https://tlk.io/84bfb8

**Comment by simonflueckiger** [comment]
Turns out that `TESSDATA_PREFIX` was not set.

**Comment by York145** [comment]
i also meet this problem
