### ISSUE TITLE
Build for tesseract 5.0.0 alpha

### ISSUE THREAD

**Issue by nakohli** [simonflueckiger/tesserocr-windows_build#9]
Hello,

Is it possible to get a build for the tesseract 5.0.0 alpha version (https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.0-alpha). I am not sure how much the API has changed so I will understand if this might not be possible to do immediately.

Thanks !

**Comment by BruceLee569** [comment]
same request, waiting support.

**Comment by zdenop** [comment]
@simonflueckiger : excellent job! Can you create also a version for 5.0.1 as it is [faster than 4.x](https://github.com/tesseract-ocr/tessdoc/blob/main/Benchmarks.md) + several problems are fixed there? 
+ maybe a version with and without OpenMP enable as it can cause problems on some configurations?

**Comment by simonflueckiger** [comment]
@zdenop sure. I'm still waiting for some help regarding https://github.com/sirfz/tesserocr/issues/295 before posting the 5.x wheels in the Releases section.

**Comment by jelledijkstra97** [comment]
Hi, is there any update on this? We would also like to use tesseract 5.x on windows!

**Comment by simonflueckiger** [comment]
tesserocr 2.5.2 with Tesseract 5.3.0 is now [released](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.5.2-tesseract-5.3.0).
